name: Daily deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy netlify
      run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
